PRA-28/Make-canvas-api
RigelKastor/tetra-tetris pull request #10
Opened 2023-09-28 15:37 UTC by IvanYank

Добавляет базовые возможности для CanvasAPI: случайную генерацию фигур, движение фигур в стороны, поворот фигур, анимация смещения фигур, отрисовка фигур.

Функция startGame() запускает установку слушателей для клавиш и отрисовывает объекты.
Функция setListeners() устанавливает слушатели вызывая функции rotateObject() и moveObject().
Функция rotateObject() отвечает за обработку нажатия клавиш, которые вращают активную фигуру.
Функция moveObject() отвечает за обработку нажатий клавиш, которые перемещают активную фигуру.
Функция drawPiece() отрисовывает составляющую ячейку, из которых состоят все фигуры.
Функция animation() запускает анимацию движения фигур и отрисовывает те, который уже были остановлены.
Функция drawObjects() выбирает случайную фигуру для отрисовки и запускает функцию animation() с выбранной фигурой.

Оставшиеся функции отвечают за отрисовку соответствующих фигур.

Для демонстрации способностей была создана страница canvas.tsx, которая находится по пути /canvas, игра запускается при нажатии на белое полотно

Надо доработать: правила окончания игра при заполнение поля, получение очков при построение линий, смещение точки построения фигуры на центр(в данный момент строится и вращается относителньо верхней левой точки).

Более детальная документация для работы с API и методами API будет сделана в другой соответствующей задаче

2023-09-29 15:14 UTC, kirafromsea commented on packages/client/src/pages/canvas/canvas.tsx
> +          position: 'absolute',
Чтобы выстроить по центру по высоте и ширине, лучше обернуть в еще один блок и у этого блока уже стили для flex прописать.
position: absolut - не очень хорошая практика в верстке для таких случаев.

2023-09-29 15:14 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +}
Вижу по коду что добавлены фигурки всех цветов, но на экран падали только 5 фигур из 7. 
Это так рандом работает или сейчас не все фигурки задействованы?

2023-09-29 15:14 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +  moveObject(e: KeyboardEvent) {
Сейчас при движении вправо/влево сдвиг происходит на 3 клетки за раз. Можно сделать, что бы смещение было на 1 клетку? Иначе управлять фигурками неудобно

2023-09-29 17:09 UTC, IvanYank commented on packages/client/src/services/CanvasAPI.ts
> +}
![image](https://github.com/RigelKastor/tetra-tetris/assets/61747305/4420fad9-77be-4042-bcb2-0716792901a4) Получается, что так работает рандом, проверил, выпали все фигуры.

2023-09-29 17:12 UTC, IvanYank commented on packages/client/src/services/CanvasAPI.ts
> +  moveObject(e: KeyboardEvent) {
Скорее всего ты несколько раз нажала на поле, возникает такой баг, по дефолту смещение только на 1 клетку. Для предотвращения такого состояния, сделал, чтобы после запуска игры баг не возникал

2023-09-29 17:12 UTC, IvanYank commented on packages/client/src/pages/canvas/canvas.tsx
> +          position: 'absolute',
Исправил

2023-09-29 18:03 UTC, IvanYank commented
Я убрал показ страницы с канвасом, все проблемы решены, но так как в основной ветке поменялась структура main файла, то довольно запарно переделывать, чтобы страница показывалась. Саму страницу оставлю, чтобы было видно, как именно надо вызывать этот класс из компонента

2023-09-30 05:00 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +}
Видно это такая особенность. Тогда ок.

2023-09-30 05:01 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +  moveObject(e: KeyboardEvent) {
Отлично!

Да, я потом тоже перезапускала и шаг был один.

2023-09-30 05:02 UTC, kirafromsea approved these changes

2023-09-30 12:13 UTC, kate-lozovaya commented on packages/client/src/pages/canvas/canvas.tsx
> +          onClick={startGame}></canvas>
Кажется, нужен `prettir`. Закрывающий тег странно разместился, и он вообще тут не нужен, можно в открывающем поставить `/>`
Лучше, чтобы html автоматически становился красивым

2023-09-30 13:17 UTC, kate-lozovaya requested changes
Вынеси отрисовку самих фигур в отдельный файл, чтобы их можно было легко менять/добавлять/убирать. И в фигурах код дублируется, его можно вынести в функцию.

2023-09-30 13:17 UTC, kate-lozovaya commented on packages/client/src/services/CanvasAPI.ts
> +  drawObjects() {
Получается очень большой класс. Может отрисовку самих фигур вынести в отдельный класс и файл?

2023-09-30 13:17 UTC, kate-lozovaya commented on packages/client/src/services/CanvasAPI.ts
> +        ]
Все кейсы выглядят похожими и строки тоже. Их можно упростить.
Например, `this.shapeWidth` и `this.shapeHeight` можно посчитать по `this.shapeMatrix`.
И отрисовывать можно тоже в цикле по 0 и 1 в `this.shapeMatrix`. 
Все эти действия лучше унести в функцию, и тут в кейсах останется только матрица и вызов функции.

2023-09-30 19:34 UTC, IvanYank commented
Код был оптимизирован: ручное изменение отрисовки было убрано, теперь всё рисуется исходя из матрицы фигуры, которая ранее поворачивалась ручным методом, теперь меняется через функцию, были убраны переменные отвечающие за ширину и высоту фигуры, теперь всё высчитывается из матрицы, был убран баг, который вызывал ошибку, если поворачивать фигуру очень низко, была добавлена новая фигура, была убрана переменная, отвечающая за состояние фигуры, была убрана страница с канвасом.

2023-10-01 10:51 UTC, kate-lozovaya approved these changes

2023-10-01 11:08 UTC, merged