PRA-24
RigelKastor/tetra-tetris pull request #13
Opened 2023-10-02 20:55 UTC by Zaldrize

1. Сверстать страницу профиля. 

2. [Подключить API смены пароля](https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_password). 

3. Сверстать компонент изменения аватара. 

4. [Подключить API для смены аватара пользователя](https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile_avatar).

Попадаем на страницу профиля по ссылке:
![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/5e916ea4-43fe-4ffd-b1ca-2d1da5cdcf0b)

![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/275660e7-8107-4709-acfe-dd8d2f0890f2)

При нажатии кнопок Change Avatar / Change Password появляются диалоговые окна:
![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/6ceffd66-a289-4cdf-ac71-e0e6cb6ae0a4)
![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/edc69158-4d77-459f-be9a-f004e09521c4)

### TBD (если есть)
При смене аватара через 0.1 сек после закрытия диалогового окна делает get-запрос данных пользователя (если делать сразу, то приходит ссылка на старый аватар). В будущем по идее от этого можно будет уйти, когда будет подключен redux.

2023-10-03 09:13 UTC, Andrew213 commented on packages/client/src/components/ChangeAvatar/ChangeAvatar.tsx
> +;    const [file, setFile] = useState<File>();
чет еслинт поплыл

2023-10-03 09:13 UTC, Andrew213 commented on packages/client/src/components/ChangeAvatar/ChangeAvatar.tsx
> +            <Form onFinish={uploadNewAvatar} form={avatarForm}>
и тут поплыл, либо у тебя форматирование не включено

2023-10-03 09:13 UTC, Andrew213 commented on packages/client/src/components/ChangeAvatar/ChangeAvatar.tsx
> +              console.log(x);
проверь все логи, почисти)

2023-10-03 09:13 UTC, Andrew213 commented on packages/client/src/pages/profile/Profile.tsx
> +              <Form className={classes.passwordForm} form={passwordForm} onFinish={changePassword}>
форматирование

2023-10-03 09:26 UTC, Andrew213 approved these changes

2023-10-03 17:01 UTC, kirafromsea commented on packages/client/src/components/Header/Header.tsx
> +        <Avatar size="xs" img={resourcesUrl + avatar} />
Раньше если аватар не задан, выводился дефолтный. Сейчас выводится пустая картинка. 
Нужно сделать, что если аватар не пришел, то или вывести дефолтную картинку или просто кружок с первой буквой имени

2023-10-03 17:03 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +    <div className={classes.profile}>
Необходимо общий компонент для страницы использовать PageFrame. Без него на странице профиля нет header и фона. Без него попадая на профиль, пользователь больше никуда не может уйти.

2023-10-03 17:05 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +    <div className={classes.profile}>
После смены аватара не произошло его обновление на странице.
В какой момент происходит смена аватара? Когда в форме нажимается upload или кнопка ОК?

2023-10-03 17:08 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +      setAvatar(DEFAULT_AVATAR);
Лучше использовать короткую запись
https://learn.javascript.ru/ifelse#uslovnyy-operator

2023-10-03 17:09 UTC, Olegas commented on packages/client/src/api/user.ts
> +    .catch((reason) => console.log(reason));
Вот тут потенциально опасная история. Ты ловишь ошибку, выводишь ее в консоль, но сам результат метода становится успешным, и тот кто вызывает функцию не получает ошибку, получает успешный, но пустой, результат

2023-10-03 17:10 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +        setAvatar(DEFAULT_AVATAR);
Аналогично с предыдущим комментом
https://learn.javascript.ru/ifelse#uslovnyy-operator

2023-10-03 17:11 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +      <Avatar size='md' img={avatar}></Avatar>
Закрывающий тег не нужен, так как внутри нет контента.
Достаточно записать  <Avatar size='md' img={avatar} />

2023-10-03 17:12 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +      <Button onClick={()=>{setIsAvatarModalOpen(true)}}>
Лишние фигурные скобки вокруг setIsAvatarModalOpen(true)

2023-10-03 17:13 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +        onOk={()=>{ setIsAvatarModalOpen(false);setTimeout(()=>onAvatarChanged(), 100);}} />
Лучше вынести в отдельную функцию handleOnOk.
Сложные группы операций в тегах трудночитаемы

2023-10-03 17:14 UTC, Olegas commented on packages/client/src/pages/profile/Profile.tsx
> +  }, [])
Не пропущена ли тут зависимость от user.avatar? Если он поменяется этот эффект не перестроится.

2023-10-03 17:15 UTC, Olegas commented on packages/client/src/pages/profile/Profile.tsx
> +      <Button onClick={()=>{setIsAvatarModalOpen(true)}}>
Этот обработчик можно завернуть в useCallback

2023-10-03 17:15 UTC, kirafromsea commented on packages/client/src/pages/profile/styles.module.less
> +  transform: translate(-50%, -50%);
ЛУчше не использовать position absolute. Современный css позволяет сделать комфортное позиционирование по центру при помощи flex особенностей

2023-10-03 17:16 UTC, Olegas commented on packages/client/src/pages/profile/Profile.tsx
> +        onOk={()=>{ setIsAvatarModalOpen(false);setTimeout(()=>onAvatarChanged(), 100);}} />
Надо выделить в отдельную функцию. Сейчас не читаемо вообще.

2023-10-03 17:16 UTC, Olegas commented on packages/client/src/pages/profile/Profile.tsx
> +            labelCol={{ span: 24 }}
Вот этот span: 24 надо взять в useMemo и использовать один на все компоненты

2023-10-03 17:17 UTC, kirafromsea commented on packages/client/src/pages/profile/styles.module.less
> +  background-color: red;
возьми, пожалуйста цвет из variables. В следующем спринте у нас предпологается функция смены темы, фиксированные цвета - вызовут сложности.

2023-10-03 17:19 UTC, Olegas requested changes
Добрый день
1. Есть проблемы по коду, написал отдельные комментарии
2. (не блокирует приемку) Местами код написан очень неаккуратно, его сложно читать. Вообще, по-умолчанию на проекте есть ci и есть prettier, который должен форматировать код автоматически. Но у вас почему-то его нет. Возможно потому, что у вас репозиторий не создан из шаблона а вместо этого склонирован шаблон

2023-10-03 17:19 UTC, kirafromsea commented on packages/client/src/pages/profile/Profile.tsx
> +  const res = [] as Array<FieldData>;
Немного устаревшая запись типа. Можно сделать по-другому:
``` Array<FieldData> => FieldData[] ```

2023-10-03 17:29 UTC, kirafromsea commented on packages/client/src/components/ChangeAvatar/ChangeAvatar.tsx
> +    } else setImageSource(DEFAULT_AVATAR)
Можно через условный оператор ? записать

2023-10-03 17:30 UTC, kirafromsea commented on packages/client/src/components/ChangeAvatar/ChangeAvatar.tsx
> +      setImageSource(resourcesUrl + props.avatar)
Чтобы постоянно не добавлять resourcesUrl можно при добавлении данных о пользователе в контекст сразу прописать resourcesUrl. Иначе сложно будет уследить где и когда нужно прописать этот урл

2023-10-03 17:31 UTC, kirafromsea commented on packages/client/src/components/ChangeAvatar/ChangeAvatar.tsx
> +  onOk: () => void
лучше такие функции называть onSubmit - в дальнейшем для тех кто будет с кодом работать, такое название будет понятней

2023-10-03 20:22 UTC, Zaldrize commented on packages/client/src/pages/profile/styles.module.less
> +  background-color: red;
исправила

2023-10-03 20:22 UTC, Zaldrize commented on packages/client/src/pages/profile/styles.module.less
> +  transform: translate(-50%, -50%);
исправила

2023-10-03 20:31 UTC, Zaldrize commented on packages/client/src/components/Header/Header.tsx
> +        <Avatar size="xs" img={resourcesUrl + avatar} />
Исправила, вынесла всю эту логику в компонент аватара

2023-10-03 20:32 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +        setAvatar(DEFAULT_AVATAR);
Исправила, вынесла всю эту логику в компонент аватара

2023-10-03 20:56 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +    <div className={classes.profile}>
После закрытия диалогового окна кнопкой OK. Upload помогает просто предварительно посмотреть новый аватар

2023-10-03 21:31 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +  const res = [] as Array<FieldData>;
исправлено

2023-10-03 21:31 UTC, Zaldrize commented on packages/client/src/components/ChangeAvatar/ChangeAvatar.tsx
> +    } else setImageSource(DEFAULT_AVATAR)
перенесла логику в компонент аватара

2023-10-03 21:32 UTC, Zaldrize commented on packages/client/src/api/user.ts
> +    .catch((reason) => console.log(reason));
добавила вывод ошибки

2023-10-03 21:32 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +      <Avatar size='md' img={avatar}></Avatar>
исправлено

2023-10-03 21:32 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +      <Button onClick={()=>{setIsAvatarModalOpen(true)}}>
вынесла в коллбэк

2023-10-03 21:35 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +      <Button onClick={()=>{setIsAvatarModalOpen(true)}}>
завернула

2023-10-03 21:35 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +        onOk={()=>{ setIsAvatarModalOpen(false);setTimeout(()=>onAvatarChanged(), 100);}} />
выделила

2023-10-03 21:36 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +            labelCol={{ span: 24 }}
исправила

2023-10-03 21:37 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +  }, [])
добавила зависимость

2023-10-04 05:45 UTC, Olegas commented on packages/client/src/api/user.ts
> +    .catch((reason) => console.log(reason));
Тут ничего не поменялось. Промис по прежнему (для внешнего наблюдателя) успешно ресолвится, правда со значением null. Ошибка снаружи будет не видна.
Сейчас вот такой вызов `putUserAvatar(...).catch(() => ...)` в случае ошибки API  никогда не перейдет в состояние "ошибка", catch никогда не сработает (будет только ошибка в консоли).

2023-10-04 05:47 UTC, Olegas commented on packages/client/src/api/user.ts
> +    .catch((reason) => console.log(reason));
Если у вас на проекте так принято обрабатывать ошибки - я тут не буду настаивать, приму работу, но это опасная практика, потому что вы не сможете отличить null, который вернулся от API и null, который случился от ошибки

2023-10-04 05:52 UTC, Olegas commented on packages/client/src/pages/profile/Profile.tsx
> +    }, 100)
Не надо так делать. У вас видимо сабмит формы и сама загрузка аватара - не связаны между собой. Есть uploadNewAvatar который собственно все и делает. И успешный сабмит формы от него не зависит никак. Надо сперва дождаться успешной загрузки, а потом уже дергать onOk. И тогда тут таймаут не понадобится и проблемы, что приходит старый аватар, не будет.

2023-10-04 05:54 UTC, Olegas requested changes
Спасибо за исправления!
Пока принять работу не могу. Основная проблема - setTimeout на обновлении аватара. Таких конструкций быть не должно (они развалятся в самый неподходящий момент когда API ответит чуть дольше чем обычно). Написал комментарий в чем там причина и как исправить.
По обработке ошибок - решение крайне спорное. Тоже написал комментарий почему именно. Но если у вас на проекте так принято ошибки обрабатывать (уже так обрабатывается в других местах) - это не будет блокировать приемку работы.
Но я бы настоятельно рекомендовал не гасить ошибки, не заменять их на null

2023-10-04 11:10 UTC, Zaldrize commented on packages/client/src/pages/profile/Profile.tsx
> +    }, 100)
Исправила. Добавила в UserContext функцию setUser, которая вызывается после успешной загрузки аватара (в это случае возвращается вся информация по пользователю с сервера), теперь аватар меняется после закрытия диалога и на странице профиля, и в хедере
![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/6742e9a7-3854-406f-a7c2-d2904fc9c81b)

2023-10-04 11:13 UTC, Zaldrize commented on packages/client/src/api/user.ts
> +    .catch((reason) => console.log(reason));
Изменила putUserAvatar - в случае неудачи он логает ошибку в консоль, а затем бросается ошибкой с сообщением, что загрузить аватар не удалось. После этого в catch уже в компоненте выводится сообщение об ошибке

2023-10-04 19:24 UTC, Olegas approved these changes
Работа принята

2023-10-05 07:20 UTC, merged