PRA-33
RigelKastor/tetra-tetris pull request #15
Opened 2023-10-07 13:50 UTC by Zaldrize

Добавила Fullscreen API, проверила в Chrome, Mozilla и Edge

![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/9219d178-c523-401d-b63f-b10c22695eeb)
Применяется ко всему элементу с игрой, по идее можно отображать сбоку счёт и т.д.

2023-10-07 14:26 UTC, kirafromsea commented on packages/client/src/pages/game/Game.tsx
> +      if (ev.key.toLocaleLowerCase() == 'f') {
А почему клавиша f, а не escape?

2023-10-07 16:43 UTC, kirafromsea approved these changes

2023-10-07 17:17 UTC, Olegas requested changes
Добрый день
1. Забыта отписка от события
2. А как выйти из полноэкранного режима?

2023-10-07 17:17 UTC, Olegas commented on packages/client/src/pages/game/Game.tsx
> +    })
Тут забыта отписка от события

2023-10-07 19:57 UTC, Zaldrize commented on packages/client/src/pages/game/Game.tsx
> +    })
добавила отписку

2023-10-07 19:58 UTC, Zaldrize commented on packages/client/src/pages/game/Game.tsx
> +    })
добавила так же выход при повторном нажатии f или модно нажать escape)

2023-10-09 07:54 UTC, Olegas approved these changes
Работа принята

2023-10-09 08:35 UTC, merged