Pra 29 game
RigelKastor/tetra-tetris pull request #18
Opened 2023-10-08 14:37 UTC by kirafromsea

### Какую задачу решаем
Реализована логика игры.
Сделано сгорание заполненной строки. Начисление очков за сжигание строки. 
Выведено поле рядом с игрой для отображения скорости и очков за игру. 
Если последняя строка поля заполнена и ни одна строчка не сгорела  игра заканчивается и выводится экран с набранными очками

### Скриншоты/видяшка (если есть)
https://drive.google.com/file/d/14CYYkNx2QCnxcA7GSl9vL65t86o_-lH-/view?usp=sharing

### TBD (если есть)

2023-10-08 16:13 UTC, IvanYank commented
При запуске игры игра зависает на пару секунд, а потом слева виднеется надпись start. В остальном всё работает исправно
![image](https://github.com/RigelKastor/tetra-tetris/assets/61747305/07f97319-3346-4ff5-aee4-ee87bd9c45cc)

2023-10-08 16:40 UTC, kirafromsea commented
> При запуске игры игра зависает на пару секунд, а потом слева виднеется надпись start. В остальном всё работает исправно ![image](https://user-images.githubusercontent.com/61747305/273460376-07f97319-3346-4ff5-aee4-ee87bd9c45cc.png)

Исправлено

2023-10-08 17:12 UTC, Andrew213 approved these changes

2023-10-09 11:56 UTC, IvanPeleshok commented on packages/client/src/pages/game/Game.tsx
> +  const api = useGameApi({
Название переменной должно носить контекст использования `gameApi`

2023-10-09 11:58 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +    for (let i = 0; i < this.fieldMatrix.length; i++) {
Достаточно сложно читать такой код

Предлагаю следующее:
- Оставлять комментарии к смысловым блокам
- Именовать переменные подходящим названием (никаких i, j и тп)

2023-10-09 12:00 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +              this.speed
Съехала переменная, лишние пробелы

2023-10-09 12:01 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +    for (let i = lineNumber; i > 0; i--) {
Аналогичное замечание, что и выше к сложности написания методов (комментируем, именуем правильно)

Вашим сокомандникам должно быть просто читать тот или иной блок без осмысления всего тела метода

2023-10-09 12:03 UTC, IvanPeleshok requested changes
Проделана большая работа, отлично потрудились! 🚀 

Есть небольшие замечания, необходима доработка

Хорошего дня :)

2023-10-09 12:54 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +    for (let i = 0; i < this.fieldMatrix.length; i++) {
> Именовать переменные подходящим названием (никаких i, j и тп)
i, j - это же стандартное типовое название для переменных, когда мы пробегаем по одномерным или двумерным массивам. Тут скорее что-то другое вызовет вопросы. Любой, кто довольно давно программирует уже на автомате пишет эти переменные при обработке массивов.

2023-10-09 12:57 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +              this.speed
Она не съехала. Это специально так сделано.

2023-10-09 13:14 UTC, kirafromsea commented on packages/client/src/pages/game/Game.tsx
> +  const api = useGameApi({
Done

2023-10-09 13:14 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +    for (let i = 0; i < this.fieldMatrix.length; i++) {
Заменила. Комментарии добавила. 
Правда стало менее читаемо.

2023-10-09 13:15 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +              this.speed
Выровняла в одну строку. Но так приходится прокручивать экран чтобы посмотреть всю строку. Особенно, если маленький монитор.

2023-10-09 13:17 UTC, kirafromsea commented on packages/client/src/services/CanvasAPI.ts
> +    for (let i = lineNumber; i > 0; i--) {
Done.
Надеюсь коллеки смогут понять новый код, который из-за названий стал сложнее (:

2023-10-10 07:42 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +              this.speed
@kirafromsea, если кажется, что ревьюер заблуждается - лучше этот момент обговорить и не вносить правки 

Имелось ввиду следующее:
```
this.animTime =
  START_ANIMATE_TIME
  - ((START_ANIMATE_TIME - MAX_SPEED_ANIMATE_TIME) / MAX_SPEED)
  * this.speed
```

2023-10-10 07:44 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +    for (let i = lineNumber; i > 0; i--) {
Возможно немного громоздко из-за больших комментариев, но разобраться в этом будет немного проще
Замечательно :)

2023-10-10 07:47 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +    for (let i = 0; i < this.fieldMatrix.length; i++) {
Предлагаю обсудить это на митинге с командой
К примеру, в разных компаниях к тем или иным вещам относятся по-разному
и в вашем случае, будет лучше писать i,j без комментариев к сложному функционалу

Уверен, что команда будет рада почитать ваши комментарии и в случае бажки быстро разберётся в коде

2023-10-10 07:47 UTC, IvanPeleshok approved these changes
Всё замечательно, апрув!

2023-10-10 08:27 UTC, merged