PRA-20__make_registration_page
RigelKastor/tetra-tetris pull request #2
Opened 2023-09-18 17:33 UTC by Andrew213

###
- Сделал архитектуру папок
- Настроил работу со стилями
- Добавил тему
- Сверстал страницу регистрации
- Настроил алиасы

### ![Screenshot from 2023-09-18 20-02-23](https://github.com/RigelKastor/tetra-tetris/assets/51080918/353799a7-cad9-4595-9132-69b3a3de262b)

2023-09-19 07:55 UTC, IvanYank commented
Всё работает, ошибок нет, показывается корректно. Но у инпутов на сайте отсутствуют аттрибуты name 
![image](https://github.com/RigelKastor/tetra-tetris/assets/61747305/daa8cb5d-6c05-4cbc-b8ad-5f3790812646)

2023-09-19 07:57 UTC, IvanYank requested changes
Всё работает, ошибок нет, показывается корректно. Но у инпутов на сайте отсутствуют аттрибуты name 
![image](https://github.com/RigelKastor/tetra-tetris/assets/61747305/725b015c-a57d-44da-9e1c-71b675298826)

2023-09-19 17:15 UTC, kirafromsea commented on packages/client/src/pages/signUp/sugnUp.tsx
> +    <Modal
А почему сделано как модельное окно? Это же просто блок с формой на странице

2023-09-19 17:16 UTC, kirafromsea commented on packages/client/src/styles/styles.less
> +} */
Коммент еще нужен будет или можно удалить?

2023-09-19 17:18 UTC, kirafromsea commented on packages/client/src/pages/signUp/sugnUp.tsx
> +          <button
Лучше вынести в UI компонент. Эта кнопка еще понадобится

2023-09-19 17:43 UTC, Andrew213 commented
> Всё работает, ошибок нет, показывается корректно. Но у инпутов на сайте отсутствуют аттрибуты name. Ещё надо уточнить стиль вёрстки для отсальных, которые будут делать другие страницы, чтобы также использовался antd, использовалось модальное окно и тп ![image](https://user-images.githubusercontent.com/61747305/268882306-725b015c-a57d-44da-9e1c-71b675298826.png)
Т.к мы используем ант, то у него своя форма и имена задаются Form.Item. Вот посмотри как это работает

https://ant.design/components/form

Это удобнее чем классическая форма имхо

2023-09-19 17:44 UTC, Andrew213 commented on packages/client/src/styles/styles.less
> +} */
удалил

2023-09-19 17:45 UTC, Andrew213 commented on packages/client/src/pages/signUp/sugnUp.tsx
> +          <button
давай пока оставим так, у анта есть свой компонент кнопки, эту кнопку я решил сделать чисто из-за стиля. Если на будет что-то нужно более сложное, то тогда вынесем

2023-09-19 17:45 UTC, Andrew213 commented on packages/client/src/pages/signUp/sugnUp.tsx
> +    <Modal
так просто было быстрее, но я переделал на обычный div

2023-09-20 10:29 UTC, IvanYank approved these changes

2023-09-20 10:30 UTC, merged