Pra 30
RigelKastor/tetra-tetris pull request #20
Opened 2023-10-08 17:33 UTC by Andrew213

Сделал кнопку возврата в меню и отображение следующей фигуры

[Screencast from 08.10.2023 20:17:24.webm](https://github.com/RigelKastor/tetra-tetris/assets/51080918/501de587-ddf7-4bf8-b95a-23dc314927dc)

2023-10-08 17:46 UTC, kirafromsea approved these changes

2023-10-09 12:09 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +      case 0:
Предлагаю вынести в константы, чтобы не было волшебных значений и виднелся контекст

Аналогично, цвета yellow, blue и т.д вынести в константы, т.к в дальнейшем возможно захочется модифицировать или переиспользовать

2023-10-09 12:11 UTC, IvanPeleshok requested changes
Проделана огромная работа, отлично потрудились!

Есть микро замечание, необходима доработка

Хорошего дня :)

2023-10-09 17:19 UTC, Andrew213 commented on packages/client/src/services/CanvasAPI.ts
> +      case 0:
у нас и так это вынесно в enum

2023-10-10 10:29 UTC, IvanPeleshok approved these changes
Отличная работа!
Поздравляю, апрув 🚀 

Хорошего дня :)

2023-10-10 10:31 UTC, IvanPeleshok commented on packages/client/src/services/CanvasAPI.ts
> +      case 0:
Речь шла о this.nextShapeName и кейсах: 0 / 1 / 2 / ...

Согласен с вами, скорее всего, это будет избыточно

Всё замечательно 😎

2023-10-10 10:49 UTC, merged