RM-36 Добавляй SSR
RigelKastor/tetra-tetris pull request #25
Opened 2023-10-20 10:35 UTC by Andrew213

https://www.youtube.com/watch?v=alHKbgJnnXw&ab_channel=Upskilling

1. Зайти в pages/сlient
2. Сбилдить для клиента (yarn buld)
3. Сбилдить для ssr (yarn:ssr)
4. Перейти в pages/server
5. Запустить дев сервер - yarn build:ssr, Запустить прод - yarn build:prod

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-20 13:25 UTC, Zaldrize approved these changes
Мне кажется, закомментированный код имеет смысл удалить, если понадобится - он легко восстановим из гита

2023-10-20 13:27 UTC, Andrew213 commented
> Мне кажется, закомментированный код имеет смысл удалить, если понадобится - он легко восстановим из гита

пусть лучше останется, чтобы не лезть в гит и не вспоминать что тут было)

2023-10-20 18:09 UTC, Olegas requested changes
Добрый день.
Есть вопросы по коду. Написал комментарии.
Требуются пояснения, пока принять не могу.

2023-10-20 18:09 UTC, Olegas commented on packages/client/index.js
> +}
Есть проблема: отличается структура приложения при построении на сервере и на клиенте. На клиенте есть обертка в виде BrowserRouter. На сервере есть другая подходящая реализация для этого

2023-10-20 18:09 UTC, Olegas commented on packages/client/src/App.tsx
> +  // }, [])
Почему весь этот код закомментирован? Почему бы его не оставить и пусть он на клиенте выполняется после оживления

2023-10-20 18:09 UTC, Olegas commented on packages/client/src/api/setupApi.ts
> +  // )
Почему весь этот код закомментирован?

2023-10-20 18:09 UTC, Olegas commented on packages/client/ssr.tsx
> +    </StaticRouter>
А вот этот renderToString - правильный. А выше тогда что за рендер?

2023-10-20 21:26 UTC, Andrew213 commented on packages/client/index.js
> +}
удалил всё, этот файл должен быть пустым

2023-10-20 21:28 UTC, Andrew213 commented on packages/client/src/App.tsx
> +  // }, [])
надо что бы проект запускался, иначе будут сыпаться ошибка. Пусть будет закомменчен, вернется как подключим редакс

2023-10-20 21:28 UTC, Andrew213 commented on packages/client/src/api/setupApi.ts
> +  // )
туда же

2023-10-20 21:28 UTC, Andrew213 commented on packages/client/ssr.tsx
> +    </StaticRouter>
не удалил при разборе сср прошлый.

2023-10-21 07:34 UTC, Olegas approved these changes
Работа принята

2023-10-27 07:37 UTC, Andrew213 commented
Не в ту ветку пр

2023-10-27 07:37 UTC, closed without merging