Pra 38
RigelKastor/tetra-tetris pull request #28
Opened 2023-10-27 21:51 UTC by Zaldrize

Добавила кнопку для авторизации с помощью OAuth
![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/b3b06a3b-d8c6-4bcf-9c0e-850f2486231e)
При нажатии отправляется запрос на получение service-id, дальше происходит редирект на страницу яндекса, в качестве коллбэка указан урл localhost:3000 (TBD - добавить везде его считывание из конфига, например)
На главной странице добавлена обработка - если есть код авторизации, с этим кодом авторизации дёргаем ручку API практикума
В итоге зашли под учёткой яндекса
![image](https://github.com/RigelKastor/tetra-tetris/assets/97559557/9dcad74c-f8df-404f-918e-f7c121af14d1)

2023-11-10 05:35 UTC, kirafromsea approved these changes

2023-11-10 15:47 UTC, Olegas commented on packages/client/src/App.tsx
> +        await signInWithYandex(code).catch(error => console.log(error))
Если тут произойдет ошибка, то catch ее просто перехватит, выведет в консоль и выполнение пойдет дальше по успешному сценарию. А дальше у тебя стоит вызов получения информации о пользователе. Если авторизация не прошла - это получается не имеет смысла. Лучше ошибку перехватить, показать пользователю и дальше не делать лишних действий

2023-11-10 15:48 UTC, Olegas commented on packages/client/src/api/oauth.ts
> +  await yandexApi.post('oauth/yandex', { code: code, redirectUri: redirectUri })
Тут нет смысла использовать async/await, лучше просто вернуть результат выполнения post - тогда в точке вызова можно нормально перехватывать ошибки и т.п.

2023-11-10 15:49 UTC, Olegas requested changes
Добрый день. Есть замечания по коду, нужно доработать

2023-11-11 12:06 UTC, Olegas approved these changes
Работа принята

2023-11-12 10:35 UTC, merged