PRA-42/Добавляет Docker
RigelKastor/tetra-tetris pull request #29
Opened 2023-11-04 14:15 UTC by IvanYank

Добавляет Docker для клиента, сервера и БД(PostgreSQL) запуск через docker-compose up server

2023-11-06 13:58 UTC, Andrew213 commented on packages/server/package.json
> +    "vite": "4.5.0"
зачем это тут?

2023-11-06 13:58 UTC, Andrew213 commented on Dockerfile.server
> +RUN rm -rf /app/packages/server/dist/ && rm -rf /app/packages/client/dist/ && cd packages/client && yarn build:ssr && yarn build
сюда видимо надо будет еще добавить client/client-dist.      Нужно ли вообще их удалять,  они же  и так удаляются при билде

2023-11-06 14:13 UTC, IvanYank commented on packages/server/package.json
> +    "vite": "4.5.0"
Потому что, когда оно всё собирается в контейнере ему нужны эти зависимости, а если их класть в дев зависимости, то они не будут тянуться и сборка будет падать

2023-11-06 14:21 UTC, IvanYank commented on Dockerfile.server
> +RUN rm -rf /app/packages/server/dist/ && rm -rf /app/packages/client/dist/ && cd packages/client && yarn build:ssr && yarn build
Изменил

2023-11-06 15:06 UTC, Andrew213 commented on packages/server/package.json
> +    "vite": "4.5.0"
почему они не будут тянуться если они в дев? зачем вит нужен на сервере?

2023-11-06 15:07 UTC, Andrew213 commented on Dockerfile.server
> +RUN rm -rf /app/packages/server/dist/ && rm -rf /app/packages/client/dist/ && rm -rf /app/packages/client/client-dist/ && cd packages/client && yarn build:ssr && yarn build
а если вообще удалить этот run? там же и так все пересобирается

2023-11-06 15:11 UTC, Andrew213 commented on packages/server/package.json
> +    "vite": "4.5.0"
мне кажется, тогда лучше сменить конфигурацию докера, сейчас это похоже на лишнюю зависимость на сервере да еще и не в дев

2023-11-06 15:34 UTC, Andrew213 approved these changes

2023-11-08 13:35 UTC, Andrew213 commented on packages/server/index.ts
> +  }
Это зачем? Некорректная переменная, и зачем она вообще

2023-11-08 13:35 UTC, Andrew213 commented on packages/server/index.ts
> +  }
там и так в srcPath путь нужный

2023-11-11 16:52 UTC, Olegas commented on Dockerfile.client
> +# CMD [ "nginx", "-g", "daemon off;", "yarn", "build;", "yarn", "build:ssr;" ]
Не надо оставлять в проекте закомментированный код

2023-11-11 16:55 UTC, Olegas commented on Dockerfile.server
> +CMD ls -la && cd packages/server && yarn dev
Очень странная команда. Выглядит как отладочный вывод которого не должно бы оказаться в проекте в итоге. Еще странно что для production-режима здесь запускается dev

2023-11-11 16:56 UTC, Olegas commented on docker-compose.yml
> +      - client
Зависимость от postgres - правильная. А вот почему тут зависимость от client? У вас же client раздает статику как я понимаю? Скорее он должен зависеть от рабочего server а не наоборот.

2023-11-11 16:57 UTC, Olegas requested changes
Добрый день.
Есть вопросы по реализации. Написал их отдельными комментариями

2023-11-12 17:21 UTC, Olegas commented
@IvanYank Объясни пожалуйста, почему контейнер client зависит от postgres? Почему не от server, который уже зависит от postgres?

2023-11-12 17:41 UTC, IvanYank commented
> @IvanYank Объясни пожалуйста, почему контейнер client зависит от postgres? Почему не от server, который уже зависит от postgres?

Я решил, что если всё запускается с запуском сервера, то зависимость можно поставить на client

2023-11-13 08:42 UTC, Olegas commented
> > @IvanYank Объясни пожалуйста, почему контейнер client зависит от postgres? Почему не от server, который уже зависит от postgres?
> 
> Я решил, что если всё запускается с запуском сервера, то зависимость можно поставить на client

Нет, так делать нельзя. Зависимости между контейнерами должны отражать реальную ситуацию. Если серверу для запуска нужен postgres - так и должно быть записано.
Иначе это может выстрелить при рефакторинге (убрали контейнер client например или что-то с ним сделали что он должен запускаться с другими зависимостями)

2023-11-13 08:56 UTC, IvanYank commented
> > > @IvanYank Объясни пожалуйста, почему контейнер client зависит от postgres? Почему не от server, который уже зависит от postgres?
> > 
> > Я решил, что если всё запускается с запуском сервера, то зависимость можно поставить на client
> 
> Нет, так делать нельзя. Зависимости между контейнерами должны отражать реальную ситуацию. Если серверу для запуска нужен postgres - так и должно быть записано.
> Иначе это может выстрелить при рефакторинге (убрали контейнер client например или что-то с ним сделали что он должен запускаться с другими зависимостями)

Хорошо, исправлю

2023-11-13 12:44 UTC, IvanYank commented
@Olegas Зависимости исправлены

2023-11-13 19:12 UTC, Olegas approved these changes
Работа принята, спасибо!

2023-11-13 20:02 UTC, merged