Pra 19 auth flow
RigelKastor/tetra-tetris pull request #9
Opened 2023-09-25 09:22 UTC by kirafromsea

### Какую задачу решаем

Подключить[ API Практикума](https://ya-praktikum.tech/api/v2/swagger/#/Auth/post_auth_signin) для авторизации пользователя.

Пользователь не может зайти ни на какую страницу проекта, если он не авторизован.

### Скриншоты/видяшка (если есть)
https://drive.google.com/file/d/1TPDhETFsuGAtRgeP5t-ZMpv0zq5lJcpN/view?usp=sharing

### TBD (если есть)

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/App.tsx
>            }
может обработку ошибок вынесем в апи? Не будем же мы это писать на каждом вызове

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/api/auth.ts
может упорядочим по принципу контроллеров, как мы делали в мессенджере?

![image](https://github.com/RigelKastor/tetra-tetris/assets/51080918/a112cb64-31bb-4feb-9bea-9d6b61691a66)

И тут же обрабатывать ошибки и делать что надо. Не вынося бизнес логику в комопненты

![image](https://github.com/RigelKastor/tetra-tetris/assets/51080918/b2c67d9c-e13b-4cdc-97de-207938ff0e21)

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/App.tsx
>            }
И ошибки из апи предлагаю сделать компонентом 
https://ant.design/components/alert

Ну или по такому типу. Не будем жы редиректить на страницу со статусом ошибки

(скорее всего это на отдельную задачу наверно)

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/api/auth.ts
> +  return yandexApi.post('auth/logout').then(res => res.data)
зачем тут then

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/api/auth.ts
>      .then(res => res.data)
и тут зачем then

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/components/Header/Header.tsx
> +    window.location.href = urls.login
вот это тут лишнее. Ты же делала юзер контекст, на нем и хорошо бы всю логику завязать.

1. По логауту - удаляем юзера из контекста
2. При переходах по страницам  делаем проверки, что юзера в контексте нет и редиректим на логин

Вот пример в доке https://reactrouter.com/en/main/fetch/redirect

Сейчас если зайти на страницу проекта (http://localhost:3000/) будет почему-то редирект на ошибку 404

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/App.tsx
> +            window.location.href = urls.errorNotFound
вот так не надо. Используй useNavigate из react-router-dom

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/components/Header/Header.tsx
> +  const handleLogout = useCallback(async () => {
зачем тут useCallback, эту функцию вообще можно вынести за компонент, если не юзаются хуки или части реакта

2023-09-25 10:43 UTC, Andrew213 commented on packages/client/src/components/Header/Header.tsx
> +  const switchShowUserMenu = useCallback(() => {
лишний useCallback. Его юзать лучше, когда ты прокидываешь функцию дальше в пропсы в другие компоненты

использование useCallback'a может привести к более низкой производительности, если оборачивать что-то легкое, что ререндерилось бы быстрее, чем "пересчитывался" бы хук

2023-09-25 10:56 UTC, kirafromsea commented on packages/client/src/App.tsx
>            }
Это только в одном месте должно быть.
Был вариант через апи, но пока не понятно нужно ли прямо туда закладывать.

У нас условие, что если пользователь заходит на закрытую страницу и он не авторизован, его должно перебросить на 401 страницу. Это не ошибка, если запрос не верный пришел. Это обработка того, что без авторизации можно попасть только на страницы логин/регистрации и страницы ошибок.

2023-09-25 10:56 UTC, kirafromsea commented on packages/client/src/App.tsx
>            }
Да, там есть отдельная задача на добавление обработки ошибок, если запрос не верно выполнен. 
Здесь вообще только авторизацию нужно было прикрутить и заблочить часть страниц для доступа.

2023-09-25 10:58 UTC, kirafromsea commented on packages/client/src/api/auth.ts
Нет. Бизнес логики не должно быть в вызовах функций. Иначе тут будут скрытые не однозначные действия.

2023-09-25 11:02 UTC, Andrew213 commented on packages/client/src/components/Header/Header.tsx
> +    window.location.href = urls.login
но давай пока оставим, мы будем подключать редакс в 6 спринте  и уйдем от контекста

2023-09-25 11:28 UTC, kirafromsea commented on packages/client/src/components/Header/Header.tsx
> +    window.location.href = urls.login
resirect не заработал. Я его в самом начале ставила вместо этого костыля. 
Но он не отрабатывал. Поэтому уже так сделала. 

Логаута у меня в задаче вообще нет. Так что я его добавила, чтобы тестить было удобней. 

> Сейчас если зайти на страницу проекта (http://localhost:3000/) будет почему-то редирект на ошибку 404
Тут пока вопрос к страницам есть. Судя по заданиям главная страница должна быть заблочена. Поэтому я ее заблокировала. Или нужно Login форму на (http://localhost:3000/)  перевести

2023-09-25 11:54 UTC, Andrew213 commented on packages/client/src/components/Header/Header.tsx
> +    window.location.href = urls.login
> resirect не заработал. Я его в самом начале ставила вместо этого костыля. Но он не отрабатывал. Поэтому уже так сделала.
> 
> Логаута у меня в задаче вообще нет. Так что я его добавила, чтобы тестить было удобней.
> 
> > Сейчас если зайти на страницу проекта (http://localhost:3000/) будет почему-то редирект на ошибку 404
> 
> Тут пока вопрос к страницам есть. Судя по заданиям главная страница должна быть заблочена. Поэтому я ее заблокировала. Или нужно Login форму на (http://localhost:3000/) перевести

 нужен не просто redirect, а navigation. По второму вопросу - думаю, что должен быть редирект на логин, иначе странно получается видеть ошибку 404

2023-09-25 11:54 UTC, kirafromsea commented on packages/client/src/components/Header/Header.tsx
> +    window.location.href = urls.login
При логауте же все равно на страницу логина должно редиректнуть?

2023-09-25 12:15 UTC, Andrew213 commented on packages/client/src/components/Header/Header.tsx
> +    window.location.href = urls.login
> При логауте же все равно на страницу логина должно редиректнуть?

ну да. тогда можно функцию оставить внутри но убрать useCallback

2023-09-25 19:29 UTC, Zaldrize commented on packages/client/src/App.tsx
> +            <Route path="/login" element={<Login />} />
Мне кажется, надо однообразно делать, типа {urls.login}

2023-09-26 13:16 UTC, Andrew213 commented on packages/client/src/api/api.ts
лишний файл. Вроде нигде не используется

2023-09-26 15:25 UTC, Andrew213 approved these changes

2023-09-27 06:53 UTC, Zaldrize approved these changes

2023-09-27 17:46 UTC, Olegas requested changes
Добрый день. Есть ряд замечаний по коду (спорные решения). Нужно либо исправить, либо объяснить почему это решение здесь подойдет

2023-09-27 17:46 UTC, Olegas commented on packages/client/src/App.tsx
> +          }
Если делается переход на другую страницу, есть ли смысл устанавливать флаг fetching и данные пользователя?

2023-09-27 17:46 UTC, Olegas commented on packages/client/src/App.tsx
> +  //TODO эта часть может понадобиться в дальнейшем для работы с бекендом. Пока оставила.
Не надо оставлять закомментированный код в проекте. Он не понадобится. Это же просто пример. Ниже вполне рабочий аналог если надо "подсмотреть" как

2023-09-27 17:46 UTC, Olegas commented on packages/client/src/api/setupApi.ts
> +          window.location.href = urls.login
Вот это решение с переходом на URL в случае ошибки выглядит очень спорным. Это будет распространяться на все запросы в приложении. Но не все ошибки потребуют перехода на другую страницу. Перекидывать на другую страницу в случае 500 - вообще неудобно. Может у сервера временные трудности и надо повторить запрос, а пользователя со страницы где он писал сообщение в форум унесло на другую страницу.

2023-09-27 17:46 UTC, Olegas commented on packages/client/src/components/PageFrame/PageFrame.tsx
> +  const activePage = window.location.pathname.substring(1).split('/')[0]
Классы (оформление) привязанные к адресам страниц - выглядит не очень надежно. Решите сменить адресацию и оформление развалится.

2023-09-27 17:46 UTC, Olegas commented on packages/client/src/pages/login/login.tsx
> +  const submitForm = useCallback(async (values: SignInType) => {
А зачем тут async?

2023-09-28 09:06 UTC, kirafromsea commented on packages/client/src/App.tsx
> +          }
Да. 
Здесь идет проверка авторизован пользователь или нет. Если нет мы редиректим на ошибку или логин.
Если да, то даем ему смотреть закрытые страницы и используем данные пользоваетеля для отрисовки интерфейса.
Фетчинг устанавливается для того, что бы до проверки пользователя не показывался интерфейс страницы. Без него, если пользователь зашел не на ту страницу (например на логин, но он уже авторизован или на страницу игры/профиля, но он не авторизован), то на мгновение появляется интерфейс страницы, а потом происходит редирект. Это не очень хороший UX для пользователя. Поэтому решила пока мы не будем точно знать есть у пользователя доступ или нет, поставить прелоадер. И параметр фетчинга как раз нужен чтобы понять отразить прелоадер или интерфейс.

Данные о пользователе так же нужны. Они устанавливаются в context. Если пользователь авторизован мы используем его данные для вывода аватара в header страниц.

2023-09-28 09:30 UTC, kirafromsea commented on packages/client/src/api/setupApi.ts
> +          window.location.href = urls.login
В случае с 401 - когда пользователь не авторизован, нам надо закрыть ему страницы, до которых у него нет доступа. Поэтому в этом случае еще и происходит проверка, на какой из страниц находится пользователь. И если это закрытая для доступа страница - мы его перенаправляем на страницу с ошибкой 401.

Согласна, решение с переадресацией в случае с 500 - сомнительная. Но!
У нас условие по заданию, что если появилась 500 ошибка - нужно отправить пользователя на страницу с этой ошибкой. Если пользователь не авторизовн, но пытается попасть на закрытую страницу - отправляем на страницу с ошибкой 401.

Поэтому для исправления этого момента на другой вариант нужно либо пояснение  к заданиям от Практикума либо убрать условия с переадресацией на страницу ошибки в случае 500 кода.

2023-09-28 12:17 UTC, Olegas commented on packages/client/src/App.tsx
> +          }
Ок, оставим давай оставим так.

2023-09-28 12:18 UTC, Olegas commented on packages/client/src/api/setupApi.ts
> +          window.location.href = urls.login
Ок, оставим давай оставим так.

2023-09-28 12:23 UTC, kirafromsea commented on packages/client/src/pages/login/login.tsx
> +  const submitForm = useCallback(async (values: SignInType) => {
Остался от первой версии реализации. Спасибо, что заметил. Убрала

2023-09-28 12:24 UTC, kirafromsea commented on packages/client/src/components/PageFrame/PageFrame.tsx
> +  const activePage = window.location.pathname.substring(1).split('/')[0]
Да. Было обсуждения в команде как лучше сделать. Изначально прокидывался тип страницы в пропсах. В команде предложили по адресу определять. 
Исправила на пропсы. Так действительно выглядит безопасней для изменений и надежней

2023-09-28 12:25 UTC, kirafromsea commented on packages/client/src/App.tsx
> +  //TODO эта часть может понадобиться в дальнейшем для работы с бекендом. Пока оставила.
Ок. Убрала. Не всматривалась что там, думала это  часть шаблона для работы с server частью приложения.

2023-09-28 16:11 UTC, Olegas approved these changes
Работа принята

2023-09-29 05:56 UTC, merged